name: New Tool Submission
description: Submit a new open source tool for evaluation
title: "[New Tool]: Tool Name - Category"
labels: ["new-tool", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a tool for evaluation! Please fill out this form as completely as possible.
  
  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: What is the name of the tool?
      placeholder: e.g., Privacy Badger
    validations:
      required: true
  
  - type: input
    id: tool-url
    attributes:
      label: Tool URL
      description: Link to the tool's website or repository
      placeholder: e.g., https://github.com/EFForg/privacybadger
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category best fits this tool?
      options:
        - Privacy
        - Security
        - Communication
        - Accessibility
        - Utility
        - Web Tool
        - Mobile App
        - AI/ML
        - Data Analysis
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe what the tool is designed to do.
      placeholder: This tool is a...
    validations:
      required: true
        
  - type: textarea
    id: core-features
    attributes:
      label: Core Features
      description: Highlight main features or functions
      placeholder: e.g., Encrypted messaging, multi-platform support, etc. List all that are compatible followed by comma.
    validations:
      required: true

  - type: input
    id: os-compatibility
    attributes:
      label: OS Compatibility
      description: What operating systems is this tool compatible with? List all that are compatible followed by comma.
      placeholder: e.g., Windows, Linux, Android, iOS
    validations:
      required: true

      
  - type: dropdown
    id: offline-functionality
    attributes:
      label: Offline Functionality
      description: Can this tool be used without an internet connection?
      options:
        - Yes
        - No
        - Partially
    validations:
      required: true

  - type: dropdown
    id: mobile-friendly
    attributes:
      label: Mobile-Friendly
      description: Does the tool work well on mobile devices?
      options:
        - Yes
        - No
        - N/A
    validations:
      required: true
        
  - type: dropdown
    id: technical-level
    attributes:
      label: Tech Skill Required
      description: What is the level of technical skill required?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true 
      
  - type: input
    id: languages-supported
    attributes:
      label: Languages Supported
      description: Number of languages or specify language list if short.
      placeholder: e.g., English, Spanish, French or 35
    validations:
      required: true     
      
  - type: textarea
    id: security-privacy-features
    attributes:
      label: Security / Privacy Features
      description: Highlight any security or privacy measures implemented.
      placeholder: e.g., End-to-end encryption, minimal tracking, open source audits, etc.
    validations:
      required: true

  - type: textarea
    id: maintenance-sustainability
    attributes:
      label: Maintenance / Sustainability
      description: What’s the current maintenance status or sustainability outlook?
      placeholder: e.g., Actively maintained by core team, community supported, etc.
    validations:
      required: true    

  - type: dropdown
    id: data-collection-level
    attributes:
      label: Data Collection Level
      description: How much user data does the tool collect?
      options:
        - None
        - Minimal
        - Extensive
    validations:
      required: true

  - type: dropdown
    id: active-development
    attributes:
      label: Active Development
      description: Is the tool actively being developed?
      options:
        - Yes
        - No
    validations:
      required: true

  - type: dropdown
    id: community-support
    attributes:
      label: Community Support
      description: Does this tool have an active community or forum?
      options:
        - Yes
        - No
        - Partially
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the current status of the tool?
      options:
        - Active
        - Inactive
        - Experimental
    validations:
      required: true

      
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How is this tool deployed/installed?
      multiple: true
      options:
        - Browser Extension
        - Desktop Application
        - Mobile App
        - Web Application
        - Command Line Tool
        - Self-hosted Service
        - Docker Container
        - Other
    validations:
      required: true
  
  - type: input
    id: license
    attributes:
      label: License
      description: Use SPDX ID if possible (e.g., MIT, GPL-3.0, Apache-2.0)
      placeholder: e.g., MIT
    validations:
      required: true

      
  - type: input
    id: cost
    attributes:
      label: Cost
      description: What is the pricing model?
      placeholder: e.g., Fully Free, Free Core, Subscription Model
    validations:
      required: true

  - type: input
    id: overall-rating
    attributes:
      label: Overall Rating
      description: Based on internal evaluation or scoring logic.
      placeholder: e.g., 4.5
    validations:
      required: true
  
  - type: checkboxes
    id: evaluation-checklist
    attributes:
      label: Evaluation Checklist
      description: Please check all that apply
      options:
        - label: I have tested this tool personally
        - label: I have reviewed the tool's documentation
        - label: I have checked the tool's license
        - label: I have tested with non-technical users
        - label: I have assessed security implications
        - label: I have documented installation steps
    validations:
      required: true
  
  - type: textarea
    id: testing-documentation
    attributes:
      label: Documentation
      description: Input Documentation here
