name: Tool Submission
description: Submit a tool with complete test results
title: "[Tool Submission]: Tool Name"
labels: ["tool-submission", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a tool with test results! This template is for submitting tools that you have thoroughly tested. If you haven't tested the tool yet, please use the "Tool Suggestion" template instead.

        Please ensure you have:
        1. Completed the [Testing Template](blob/main/docs/technical/assessment/TOOL_TEMPLATE.md)
        2. Documented all test results
        3. Included performance metrics
        4. Assessed security implications
        5. Documented installation steps

  - type: markdown
    attributes:
      value: |
        ## Basic Information

  - type: input
    id: tool-name
    attributes:
      label: Tool Name
      description: What is the name of the tool?
      placeholder: e.g., Privacy Badger
    validations:
      required: true

  - type: input
    id: tool-url
    attributes:
      label: Tool URL
      description: Link to the tool's website or repository
      placeholder: e.g., https://github.com/EFForg/privacybadger
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category best fits this tool?
      options:
        - File Transfer
        - Messaging
        - Browser
        - Password Management
        - PasteBins
        - Office Suites
        - Notebooks
        - Multi-factor Authentication
        - VPN Services
        - Search Engines
        - Content Blockers
        - AI Chat
        - Data & Metadata Redaction
        - Email Clients
        - Encryption
        - Language Tools
        - Desktop/PC
        - Document Collaboration
        - OS
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe what the tool is designed to do
      placeholder: This tool is a...
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the current status of the tool?
      options:
        - "Active"
        - "Inactive"
        - "Experimental"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Core Features & Compatibility

  - type: textarea
    id: core-features
    attributes:
      label: Core Features
      description: List the main features of the tool (comma-separated)
      placeholder: e.g., End-to-end Encryption, Self-destructing Messages, Voice/Video Calls
    validations:
      required: true

  - type: textarea
    id: os-compatibility
    attributes:
      label: Os Compatibility
      description: List all supported operating systems (comma-separated)
      placeholder: e.g., Windows, Linux, macOS, Android
    validations:
      required: true

  - type: dropdown
    id: offline-functionality
    attributes:
      label: Offline Functionality
      description: Can the tool be used offline?
      options:
        - "Yes"
        - "No"
        - "Partially"
    validations:
      required: true

  - type: dropdown
    id: mobile-friendly
    attributes:
      label: Mobile Support
      description: Is the tool mobile-friendly?
      options:
        - "Yes"
        - "No"
        - "Partially"
    validations:
      required: true

  - type: textarea
    id: languages-supported
    attributes:
      label: Languages Supported
      description: List supported languages or number of languages
      placeholder: e.g., English, Chinese, Japanese, Korean or "32 languages"
    validations:
      required: true

  - type: dropdown
    id: technical-level
    attributes:
      label: Technical Level
      description: What level of technical expertise is required?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Security & Privacy

  - type: textarea
    id: security-privacy-features
    attributes:
      label: Security and Privacy Features
      description: List key security and privacy features (comma-separated)
      placeholder: e.g., End-to-end Encryption, 2FA, Data Encryption at Rest
    validations:
      required: true

  - type: dropdown
    id: data-collection-level
    attributes:
      label: Data Collection Level
      description: How much user data does the tool collect?
      options:
        - "No Data Collection"
        - "Minimal"
        - "Extensive"
    validations:
      required: true

  - type: input
    id: security-privacy-rating
    attributes:
      label: Security and Privacy Rating
      description: Rate the security and privacy features from 1-5
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Deployment & Technical

  - type: textarea
    id: deployment-architecture
    attributes:
      label: Deployment Architecture
      description: Describe how the tool is deployed
      placeholder: e.g., Standalone software, Client-server application, Browser extension
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: License
      description: What license is the tool under? (Use SPDX ID if possible)
      placeholder: e.g., MIT, GPL-3.0, Apache-2.0
    validations:
      required: true

  - type: dropdown
    id: cost
    attributes:
      label: Cost Structure
      description: What is the cost structure?
      options:
        - "Fully Free"
        - "Free Core"
        - "Subscription Model"
        - "One-time Purchase"
        - "Other"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Maintenance & Support

  - type: textarea
    id: maintenance-sustainability
    attributes:
      label: Maintenance Sustainability
      description: Describe the project's maintenance status and funding
      placeholder: e.g., Monthly updates, funded by donations, active development team
    validations:
      required: true

  - type: dropdown
    id: community-support
    attributes:
      label: Community Support
      description: Is there active community support?
      options:
        - "Yes"
        - "No"
        - "Limited"
    validations:
      required: true

  - type: input
    id: maintenance-sustainability-rating
    attributes:
      label: Maintenance Sustainability Rating
      description: Rate the maintenance and sustainability from 1-5
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Performance & Ratings

  - type: input
    id: operational-functionality-rating
    attributes:
      label: Operational Functionality Rating
      description: Rate the operational functionality from 1-5
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: input
    id: usability-rating
    attributes:
      label: Usability Rating
      description: Rate the usability from 1-5
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: input
    id: effectiveness-reliability-rating
    attributes:
      label: Effectiveness and Reliability Rating
      description: Rate the effectiveness and reliability from 1-5
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: input
    id: overall-rating
    attributes:
      label: Overall Rating
      description: The overall rating based on weighted scores (calculated automatically)
      placeholder: e.g., 4.5
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Documentation & Testing

  - type: textarea
    id: full-documentation
    attributes:
      label: Full Documentation
      description: Please provide only link/file to the full documentation for this tool
      placeholder: Ex. "https://github.com/user-attachments/files/20002594/example.pdf"
    validations:
      required: true

  - type: input
    id: version-tested
    attributes:
      label: Version Tested
      description: Which version of the tool did you test?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: date-tested
    attributes:
      label: Date Tested
      description: When was this tool tested? (YYYY-MM-DD)
      placeholder: e.g., 2024-03-20
    validations:
      required: true

  - type: textarea
    id: testing-environment
    attributes:
      label: Testing Environment
      description: Describe the environment used for testing (OS, hardware, network, etc.)
      placeholder: e.g., Windows 11, 16GB RAM, 100Mbps broadband
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information

  - type: textarea
    id: limitations-vulnerabilities
    attributes:
      label: Limitations and Vulnerabilities
      description: Describe any known limitations or vulnerabilities
      placeholder: e.g., No offline support, requires phone number, limited file size
    validations:
      required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or context about your testing
      placeholder: Additional notes about your testing process or findings...

  - type: checkboxes
    id: evaluation-checklist
    attributes:
      label: Submission Checklist
      description: Please check all that apply
      options:
        - label: I have completed the testing template
        - label: I have documented all test results
        - label: I have included performance metrics
        - label: I have assessed security implications
        - label: I have documented installation steps
    validations:
      required: true 
