name: Process Tools

on:
  issues:
    types: [labeled]

concurrency: add_tool

jobs:
  update-tools-json:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Event Data
        run: |
          echo "Event Path: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Execute process_tools_submission.py
        id: python_script
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          echo "Running script..."
          python .github/scripts/process_tools_submission.py $GITHUB_EVENT_PATH

      - name: Commit Updated tools.json
        if: success()
        run: |
          git config --local user.email ${{ steps.python_script.outputs.commit_email }}
          git config --local user.name ${{ steps.python_script.outputs.commit_username }}
          git add .github/scripts/tools.json
          git diff-index --quiet HEAD || git commit -m "${{ steps.python_script.outputs.commit_message }}" --allow-empty

      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: addingScripts

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Auto Close Issue
        if: success()
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "✅ Tool submission approved and added."

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Problem With Action
        if: failure()
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "❌ GitHub Action failed. Error: ${{ steps.python_script.outputs.error_message }}"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
