# GitHub Actions workflow that automatically updates the README.md file. This workflow runs periodically or when triggered by changes to keep the tools list, statistics, and other dynamic content in the README up to date.
name: Update README with Approved Tools

on:
  push:
    branches:
      - main
    paths:
      - ".github/scripts/tools.json"
      - "tools.json"
  workflow_dispatch:  # Manual trigger option

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Path Changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD~1 HEAD

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run the script to update README
        id: update_readme
        run: |
          python .github/scripts/update_readme.py

      - name: Get Commit Info
        id: commit_info
        run: |
          echo "commit_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT
          echo "commit_username=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT

      - name: Commit changes to README
        if: success()
        run: |
          git config --local user.email "${{ steps.commit_info.outputs.commit_email }}"
          git config --local user.name "${{ steps.commit_info.outputs.commit_username }}"
          git add README.md
          git diff-index --quiet HEAD || (git commit -a -m "Update README with approved tools" --allow-empty)

      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Problem With Action
        if: failure()
        run: |
          echo "Error updating README. Please check the logs for details."
          exit 1
