# GitHub Actions workflow that automatically updates the README.md file. This workflow runs periodically or when triggered by changes to keep the tools list, statistics, and other dynamic content in the README up to date.
name: Update README with Approved Tools

on:
  push:
    branches:
      - addingScripts
    paths:
      - ".github/scripts/tools.json"
      - "README.md"
    workflow_dispatch:  # Manual trigger option

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run the script to update README
        run: |
          python .github/scripts/update_readme.py

      - name: Commit changes to README
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update README with approved tools"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
