# GitHub Actions workflow that automatically updates the README.md file. This workflow runs periodically or when triggered by changes to keep the tools list, statistics, and other dynamic content in the README up to date.
name: Update README with Approved Tools

on:
  push:
    branches:
      - main
    paths:
      - "tools.json"
  workflow_dispatch:  # Manual trigger option

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global pull.rebase true
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Debug Repository State
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "tools.json contents:"
          cat tools.json || echo "tools.json not found"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run the script to update README
        id: update_readme
        run: |
          cd .github/scripts
          python update_readme.py

      - name: Commit changes to README
        if: success()
        run: |
          git add README.md
          git diff-index --quiet HEAD || (git commit -a -m "Update README with approved tools" --allow-empty)

      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Problem With Action
        if: failure()
        run: |
          echo "Error updating README. Please check the logs for details."
          exit 1
